version: "3.9"
services:
  python-server:
    build:
      context: ./
      args:
        - APP_FOLDER=app
    image: python-server-image
    container_name: python-server
    ports:
      - "8080:8082"
    volumes:
      - type: bind
        source: source
        target: /usr/src/app/source
    environment:
      ENV: development
